GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/Service_Request_Document__c.object-meta.xml
<CustomObject>
    <label>Service  Request Document</label>
    <nameField>
        <displayFormat>SRD-{000000}</displayFormat>
        <label>Service  Request Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service  Request Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/fields/Is_Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Is_Reviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Reviewed</label>
    <type>Checkbox</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/fields/Reviewed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_Date_Time__c</fullName>
    <label>Reviewed Date Time</label>
    <type>DateTime</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/fields/Service_Request_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request Line Item</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Request_Line_Item__c.Reason_Code__c</field>
            <operation>notEqual</operation>
            <value>Cancel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Request_Line_Item__c</referenceTo>
    <relationshipLabel>Service Request Documents</relationshipLabel>
    <relationshipName>Service_Request_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Delivery Failed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Line_Item__c/Service_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{000000}</displayFormat>
        <label>Service Request Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>QA In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>QAComplete</fullName>
                <isActive>false</isActive>
                <label>QAComplete</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/classes/ServiceRequestLineItemRecsController.cls
public class ServiceRequestLineItemRecsController {
/************************************************************
* @File Name          : ServiceRequestLineItemRecsController
* @Description        : 
* @Author             : AppShark Team
* @Created Date       : 
* @Last Updated Date  : 
**********************************************************/
    @AuraEnabled(cacheable=true)
    public static list<Service_Request_Line_Item__c> getServiceRequestDetailrecords(Id taskid){
        Task TaskDtls= TaskQuerySelector.getTaskdetails(taskid);
        list<Service_Request_Line_Item__c> srdlist= new list<Service_Request_Line_Item__c>();
        if(TaskDtls!=null &&TaskDtls.WhatId!=null){
            srdlist=SRLineItemQueryselector.getrelatedServiceReqDetails(new set<id>{TaskDtls.WhatId}).get(TaskDtls.WhatId);
        }
        
        return srdlist;
    }
    
    @AuraEnabled(cacheable=true)
    public static list<Service_Request_Document__c> getRPDrecords(Id recid){ 
        String sObjName = recid.getSObjectType().getDescribe().getName();
        list<Service_Request_Document__c> rpdlist= new list<Service_Request_Document__c>();
        if(sObjName=='Task'){
            system.debug('taskid'+recid);
            Task TaskDtls= TaskQuerySelector.getTaskdetails(recid);
            if(TaskDtls!=null &&TaskDtls.WhatId!=null){
                rpdlist=ServiceRequestQuerySelector.getRPDlistmapWithSR(new set<id>{TaskDtls.WhatId}).get(TaskDtls.WhatId);
            }
        }else if(sObjName==constants.OBJECT_NAME_SRD){
            set<Id> srdids=new set<Id>();
            srdids.add(recid);
            rpdlist=SRLineItemQueryselector.getRPDlistmapWithSRD(srdids).get(recid);
        }
        return rpdlist;
    }
    
    @AuraEnabled
    public static void updateRPDStatus(list<string> rpdids, string status){                
        list<Service_Request_Document__c> updaterpdlist= new list<Service_Request_Document__c>();
        for(Service_Request_Document__c rpd : [SELECT Id, Status__c, Is_Reviewed__c, Reviewed_Date_Time__c 
                                                 FROM Service_Request_Document__c
                                                 WHERE Id IN :rpdids])
        {
            rpd.Is_Reviewed__c = true;
            rpd.Reviewed_Date_Time__c = System.now();
            if(status == 'Archived')
                rpd.Status__c = 'Archived';
            updaterpdlist.add(rpd);
        }
        if(updaterpdlist != null && updaterpdlist.size() > 0){
            update updaterpdlist;
        }
    }
    
    @AuraEnabled
    public static void updateServiceRequestDocument(Service_Request_Document__c updatedDocument){
        Service_Request_Document__c existingDocument = [SELECT Id, Name, Description__c, Status__c 
                                                       FROM Service_Request_Document__c 
                                                       WHERE Id = :updatedDocument.Id];
        existingDocument.Name = updatedDocument.Name;
        existingDocument.Description__c = updatedDocument.Description__c;
        existingDocument.Status__c = updatedDocument.Status__c;
        
        update existingDocument;
    }
}