GloablServices/keshavglobal/force-app/main/default/objects/Service_Request__c/Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Service Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complete – All Records Received</fullName>
            </value>
            <value>
                <fullName>Complete - No Records Received</fullName>
            </value>
            <value>
                <fullName>Complete – Partial Records Received</fullName>
            </value>
            <value>
                <fullName>Terminate</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Complete Full</fullName>
                <isActive>false</isActive>
                <label>Complete Full</label>
            </value>
            <value>
                <fullName>Complete No Records</fullName>
                <isActive>false</isActive>
                <label>Complete No Records</label>
            </value>
            <value>
                <fullName>Complete Partial</fullName>
                <isActive>false</isActive>
                <label>Complete Partial</label>
            </value>
            <value>
                <fullName>Complete-Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Complete-Withdrawn</label>
            </value>
            <value>
                <fullName>Complete-Withdrawn-Bill</fullName>
                <isActive>false</isActive>
                <label>Complete-Withdrawn-Bill</label>
            </value>
            <value>
                <fullName>Complete-Withdrawn-Full</fullName>
                <isActive>false</isActive>
                <label>Complete-Withdrawn-Full</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>DocumentsSentOut</fullName>
                <label>Documents Sent Out</label>
            </value>
            <value>
                <fullName>Documents In Progress</fullName>
            </value>
            <value>
                <fullName>QA Complete</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Complete Full</fullName>
                <isActive>false</isActive>
                <label>Complete Full</label>
            </value>
            <value>
                <fullName>Complete No Records Returned</fullName>
                <isActive>false</isActive>
                <label>Complete No Records Returned</label>
            </value>
            <value>
                <fullName>Complete Partial</fullName>
                <isActive>false</isActive>
                <label>Complete Partial</label>
            </value>
            <value>
                <fullName>Documents Sent</fullName>
                <isActive>false</isActive>
                <label>Documents Sent</label>
            </value>
            <value>
                <fullName>Late Cancel</fullName>
                <isActive>false</isActive>
                <label>Late Cancel</label>
            </value>
            <value>
                <fullName>SentToCase360</fullName>
                <isActive>false</isActive>
                <label>Sent To Case 360</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/Service_Request_Document__c.object-meta.xml
<CustomObject>
    <label>Service  Request Document</label>
    <nameField>
        <displayFormat>SRD-{000000}</displayFormat>
        <label>Service  Request Documents Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service  Request Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipName>Service_Request_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/fields/Service_Request_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Service_Request_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request Line Item</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Service_Request_Line_Item__c.Reason_Code__c</field>
            <operation>notEqual</operation>
            <value>Cancel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Request_Line_Item__c</referenceTo>
    <relationshipLabel>Service Request Documents</relationshipLabel>
    <relationshipName>Service_Request_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Received</fullName>
                <default>true</default>
                <label>Received</label>
            </value>
            <value>
                <fullName>Matched</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Delivery Failed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Fax_job__c/Service_Request_Fax_job__c.object-meta.xml
<CustomObject>
    <label>Service Request Fax job</label>
    <nameField>
        <displayFormat>SfxJ-{000000}</displayFormat>
        <label>Service Request Fax job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Request Fax jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Fax_job__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Service Request Fax jobs</relationshipLabel>
    <relationshipName>Service_Request_Fax_jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Fax_job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Line_Item__c/Service_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Request Line Item</label>
    <nameField>
        <displayFormat>SRLI-{000000}</displayFormat>
        <label>Service Request Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Line_Item__c/fields/Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Document Received</fullName>
            </value>
            <value>
                <fullName>Partial Document Received</fullName>
            </value>
            <value>
                <fullName>No Records</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Incorrect Document Received</fullName>
            </value>
            <value>
                <fullName>Complete-Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Complete-Withdrawn</label>
            </value>
            <value>
                <fullName>Complete-Withdrawn-Bill</fullName>
                <isActive>false</isActive>
                <label>Complete-Withdrawn-Bill</label>
            </value>
            <value>
                <fullName>Complete-Withdrawn-Full</fullName>
                <isActive>false</isActive>
                <label>Complete-Withdrawn-Full</label>
            </value>
            <value>
                <fullName>Terminate</fullName>
                <isActive>false</isActive>
                <label>Terminate</label>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
                <isActive>false</isActive>
                <label>Withdrawn</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Line_Item__c/fields/Service_Request__c.field-meta.xml
<CustomField>
    <fullName>Service_Request__c</fullName>
    <label>Service Request</label>
    <referenceTo>Service_Request__c</referenceTo>
    <relationshipLabel>Service Requests Line Item</relationshipLabel>
    <relationshipName>Service_Requests_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Service_Request_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>QA In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
                <isActive>false</isActive>
                <label>Cancel</label>
            </value>
            <value>
                <fullName>QAComplete</fullName>
                <isActive>false</isActive>
                <label>QAComplete</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/objects/Task_Configuration__mdt/Task_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for Task Creation</description>
    <label>Task Configuration</label>
    <pluralLabel>Task Configuration</pluralLabel>
</CustomObject>

GloablServices/keshavglobal/force-app/main/default/objects/Task_Configuration__mdt/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

GloablServices/keshavglobal/force-app/main/default/classes/TaskUtility.cls
public with sharing class TaskUtility {
    public static Id FollowupRecordtypeId = RecordTypeUtil.getRecordTypeId(Task.SObjectType, Constants.FOLLOWUP_RECORDTYPE  , false);
    public static Id ReviewRecordtypeId = RecordTypeUtil.getRecordTypeId(Task.SObjectType, Constants.QA_REVIEW_RECORDTYPE  , false);
    
    public static void CreateTask(set<Id> relatedObjids,string Tasktype, string recurrenceInterval, DateTime endDate){
        list<Task> newFollowupTask= new list<Task>();
        BusinessDaysUtility bdu = new BusinessDaysUtility();
        map<Id,Service_Request__c> srMap = new map<Id,Service_Request__c>();
        map<id,Service_Request_Fax_job__c> RightfaxDetailMap = new map<id,Service_Request_Fax_job__c>();
        map<Id,Service_Request_Document__c> rpdDetailMap = new map<Id,Service_Request_Document__c>();
        map<Id,Service_Request_Line_Item__c> srdMap = new map<Id,Service_Request_Line_Item__c>();
        Map<string,Task_Configuration__mdt> taskmdtMap = new Map<string,Task_Configuration__mdt>();
        Id Followupqueueid;
        Id Reviewqueueid;
        Id CoversheetFailurequeueid;
        Id TaskOwnerId;
        Id taskrecordtypeId;
        if(Tasktype == Constants.TASKTYPE_FOLLOWUP){
            srMap = ServiceRequestQuerySelector.getServiceRequestMap(relatedObjids);
            RightfaxDetailMap = ServiceRequestQuerySelector.getSRRightfaxjobDetails(relatedObjids);
            Followupqueueid= CaseQuerySelector.getQueueId(Constants.SERVICEREQUEST_FOLLOWUP_QUEUE);
            taskmdtMap = TaskQuerySelector.gettasktypeconfigDetails(new set<string>{Constants.TASKTYPE_FOLLOWUP}); 
            TaskOwnerId=Followupqueueid;
            taskrecordtypeId = FollowupRecordtypeId; 
        }
        else if(Tasktype == Constants.TASKTYPE_REVIEW){
            srMap = ServiceRequestQuerySelector.getServiceRequestMap(relatedObjids);
            srdMap = SRLineItemQueryselector.getServiceRequestDetaillist(relatedObjids);
            rpdDetailMap = SRLineItemQueryselector.getRPDDetaillist(relatedObjids);
            Reviewqueueid= CaseQuerySelector.getQueueId(Constants.SERVICEREQUEST_REVIEW_QUEUE);
            taskmdtMap = TaskQuerySelector.gettasktypeconfigDetails(new set<string>{Constants.TASKTYPE_REVIEW});
            TaskOwnerId=Reviewqueueid;
            taskrecordtypeId = ReviewRecordtypeId; 
        }
        else if(Tasktype == Constants.TASKTYPE_FAX_FAILED){
            srMap = ServiceRequestQuerySelector.getServiceRequestMap(relatedObjids);
            RightfaxDetailMap = ServiceRequestQuerySelector.getSRRightfaxjobDetails(relatedObjids);
            CoversheetFailurequeueid = CaseQuerySelector.getQueueId(Constants.COVERSHEETFAXFAILURE_FOLLOWUP_QUEUE);
            taskmdtMap = TaskQuerySelector.gettasktypeconfigDetails(new set<string>{Constants.TASKTYPE_FAX_FAILED});
             TaskOwnerId= CoversheetFailurequeueid;
            taskrecordtypeId = FollowupRecordtypeId; 
        }
        try{
            for(Id objid: relatedObjids){
                if(srMap.get(objid).Status__c!=Constants.SR_STATUS_COMPLETE){
                    for(Task_Configuration__mdt taskconfig:taskmdtMap.values()){
                        Task objTask = new Task();
                        objTask.RecordTypeId = taskrecordtypeId;
                        objTask.Task_Type__c = taskconfig.Task_Type__c;
                        objTask.WhatId = objid;
                        objTask.RecurrenceInterval__c = recurrenceInterval;
                        objTask.EndDate__c = endDate;
                        objTask.JobId__c = String.valueOf(System.currentTimeMillis());
                        
                        // Rest of the code remains the same...
                        
                        newFollowupTask.add(objTask);
                    }
                }
            }
            if(newFollowupTask!= null && newFollowupTask.size()>0)
                insert newFollowupTask;
        }catch(Exception e){
            GDSException.LogException(e);
        } 
    }
    public static list<Service_Request_Line_Item__c>  UpdateAllServiceRequestDetailStatus(list<Service_Request_Line_Item__c> SRDlist){
        list<Service_Request_Line_Item__c> updateSRDlist= new list<Service_Request_Line_Item__c>();
        for(Service_Request_Line_Item__c SRDetails: SRDlist){
            if(SRDetails.Status__c != constants.SRD_STATUS_COMPLETE){
                SRDetails.Status__c = constants.SRD_STATUS_COMPLETE;
                if(SRDetails.Reason_Code__c == null || SRDetails.Reason_Code__c==''){
                    SRDetails.Reason_Code__c = Constants.SRD_RESULT_NO_RECORDS;       
                }
                updateSRDList.add(SRDetails);
            }
        }	
        return updateSRDlist;
    }
} 